# Generated by Django 5.1.15 on 2026-09-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_accounts", "0013_orbita_add_x_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="platform_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
